### ISSUE TITLE
The Citeseer dataset appears to be missing

### ISSUE THREAD

**Issue by zhongjian-zhang** [franciscoliu/graphprompter#1]
Hi!
The data seems to be incomplete under the citeseer_orig folder, can you provide the complete Citeseer dataset?
Looking forword to your reply!

**Comment by franciscoliu** [comment]
Thank you for the question, have you tried to download the zip file and unzip it before you run the preprocessing command?
Additionally, here are some possible problems that may arise during data preprocessing: https://github.com/XiaoxinHe/TAPE/issues/10

**Comment by zhongjian-zhang** [comment]
thank for your reply, but I don't know where to download the citeseer dataset zip. In the citeseer_orig folder, the size of files is very small, I don't think it's the original data file.
<img width="1504" alt="image" src="https://github.com/franciscoliu/graphprompter/assets/59616556/b1a336e1-acfc-484d-b6e9-c89d38578808">
<img width="1487" alt="image" src="https://github.com/franciscoliu/graphprompter/assets/59616556/c7646d5b-da7b-417e-a7f0-62e8e79de060">

**Comment by franciscoliu** [comment]
I just double checked the citeseer data folder and found the there's one file missing (citeseer_texts.txt). I have uploaded the file to this repository. Could you double check?

**Comment by zhongjian-zhang** [comment]
Thank for you reply. There are remain some error, please check the file [citeseer.cites](https://github.com/franciscoliu/graphprompter/blob/main/dataset/citeseer_orig/citeseer.cites) and [citeseer.content](https://github.com/franciscoliu/graphprompter/blob/main/dataset/citeseer_orig/citeseer.content), I find the two file just have three row content.

**Comment by franciscoliu** [comment]
The data is being handled in preprocess file. What error do you get if you run:

python -m src.dataset.preprocess.citeseer

**Comment by zhongjian-zhang** [comment]
the error as follow:
<img width="1582" alt="image" src="https://github.com/franciscoliu/graphprompter/assets/59616556/768c10f6-e26e-4df9-a984-3cc09b7b76f9">

**Comment by franciscoliu** [comment]
Ah, I see the problem now. Just re-uploaded those two files, there might be an error when I uploaded them. Could you double check?

**Comment by zhongjian-zhang** [comment]
Thank you for your patience. There are no more questions now.
