### ISSUE TITLE
申请大模型被拒

### ISSUE THREAD

**Issue by shaieesss** [franciscoliu/graphprompter#5]
作者您好，我从hugging face上刚创立一个账号申请llama2 的使用，但是其作者拒绝了，因此想问一下您是怎么申请到的，或者从哪里下载

**Comment by franciscoliu** [comment]
您好，我并没有遇到过这样的问题，我用的是gmail的account的账号申请的，是不是您的email地址比较sensitive？

**Comment by franciscoliu** [comment]
Here is the link of download: https://llama.meta.com/llama-downloads
